version: '3.8'

services:
  # Redis服务
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    command: redis-server --save 20 1 --loglevel warning

  # PostgreSQL服务（带向量插件）
  postgres:
    image: ankane/pgvector:v0.4.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_service
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    restart: always

  # Jaeger服务
  jaeger:
    image: jaegertracing/all-in-one:1.41
    container_name: jaeger
    ports:
      - "6831:6831/udp"  # Jaeger客户端发送数据的端口
      - "16686:16686"    # Jaeger UI端口
    environment:
      COLLECTOR_ZIPKIN_HOST_PORT: ":9411"
    restart: always

volumes:
  redis-data:
  postgres-data: